# Generated by Django 4.0 on 2022-02-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_seller_pic1_seller_pic2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='pic2',
        ),
    ]
