# Generated by Django 4.0 on 2022-02-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_seller_pic2'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
