# Generated by Django 4.0 on 2022-02-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
