# Generated by Django 4.0 on 2022-02-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0025_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
