# Generated by Django 4.0 on 2022-02-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_buyer_address1_buyer_address2_buyer_city_buyer_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
