# Generated by Django 4.0 on 2022-02-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0030_buyer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='pic1',
            new_name='pic',
        ),
    ]
