# Generated by Django 4.0 on 2022-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0033_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='subsrcibe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
