# Generated by Django 4.0 on 2022-05-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_subsrcibe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subsrcibe',
            new_name='Subscribe',
        ),
    ]
